ConferencePlanner/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ConferencePlanner.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ConferencePlanner/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ConferenceDTO;
using ConferencePlanner.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ConferencePlanner.Pages
{
    public class IndexModel : PageModel
    {
        protected readonly IApiClient _apiClient;

        [TempData]
        public string Message { get; set; }

        public bool IsAdmin { get; set; }

        public List<int> UserSessions { get; set; }

        public bool ShowMessage => !string.IsNullOrEmpty(Message);

        public IndexModel(IApiClient apiClient)
        {
            _apiClient = apiClient;
        }

        public IEnumerable<IGrouping<DateTimeOffset?, SessionResponse>> Sessions { get; set; }

        public IEnumerable<(int Offset, DayOfWeek? DayofWeek)> DayOffsets { get; set; }

        public int CurrentDayOffset { get; set; }

        public async Task OnGet(int day = 0)
        {
            CurrentDayOffset = day;

            var sessions = await GetSessionsAsync();

            var userSessions = await _apiClient.GetSessionsByAttendeeAsync(User.Identity.Name);

            var startDate = sessions.Min(s => s.StartTime?.Date);
            var endDate = sessions.Max(s => s.EndTime?.Date);

            var numberOfDays = ((endDate - startDate)?.Days) + 1;

            DayOffsets = Enumerable.Range(0, numberOfDays ?? 0)
                .Select(offset => (offset, (startDate?.AddDays(offset))?.DayOfWeek));

            var filterDate = startDate?.AddDays(day);

            Sessions = sessions.Where(s => s.StartTime?.Date == filterDate)
                               .OrderBy(s => s.TrackId)
                               .GroupBy(s => s.StartTime)
                               .OrderBy(g => g.Key);

            UserSessions = userSessions.Select(s => s.ID).ToList();
        }

        protected virtual Task<List<SessionResponse>> GetSessionsAsync()
        {
            return _apiClient.GetSessionsAsync();
        }

        public async Task<IActionResult> OnPostAsync(int sessionId, int day = 0)
        {
            CurrentDayOffset = 0;
            await _apiClient.AddSessionToAttendeeAsync(User.Identity.Name, sessionId);

            return RedirectToPage(new { day });
        }

        public async Task<IActionResult> OnPostRemoveAsync(int sessionId, int day = 0)
        {
            CurrentDayOffset = day;
            await _apiClient.RemoveSessionFromAttendeeAsync(User.Identity.Name, sessionId);

            return RedirectToPage(new { day });
        }
    }

}

ConferencePlanner/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ConferencePlanner.Filters;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ConferencePlanner.Pages
{
    [SkipWelcome]
    public class LoginModel : PageModel
    {
        private readonly IAuthenticationSchemeProvider _authSchemeProvider;

        public LoginModel(IAuthenticationSchemeProvider authSchemeProvider)
        {
            _authSchemeProvider = authSchemeProvider;
        }

        public IEnumerable<AuthenticationScheme> AuthSchemes { get; set; }

        public async Task<IActionResult> OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToPage("/Index");
            }

            AuthSchemes = await _authSchemeProvider.GetRequestHandlerSchemesAsync();

            return Page();
        }

        public IActionResult OnPost(string scheme)
        {
            return Challenge(new AuthenticationProperties { RedirectUri = Url.Page("/Index") }, scheme);
        }
    }
}

ConferencePlanner/Pages/MyAgenda.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using ConferenceDTO;
using ConferencePlanner.Services;

namespace ConferencePlanner.Pages
{
    public class MyAgendaModel : IndexModel
    {
        public MyAgendaModel(IApiClient client)
            : base(client)
        {

        }
        protected override Task<List<SessionResponse>> GetSessionsAsync()
        {
            return _apiClient.GetSessionsByAttendeeAsync(User.Identity.Name);
        }
    }
}

ConferencePlanner/Pages/Search.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ConferenceDTO;
using ConferencePlanner.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ConferencePlanner.Pages
{
    public class SearchModel : PageModel
    {
        private readonly IApiClient _apiClient;

        public SearchModel(IApiClient apiClient)
        {
            _apiClient = apiClient;
        }

        public string Term { get; set; }

        public List<object> SearchResults { get; set; }

        public async Task OnGetAsync(string term)
        {
            Term = term;
            var results = await _apiClient.SearchAsync(term);
            SearchResults = results.Select(sr =>
            {
                switch (sr.Type)
                {
                    case SearchResultType.Session:
                        return (object)sr.Value.ToObject<SessionResponse>();
                    case SearchResultType.Speaker:
                        return (object)sr.Value.ToObject<SpeakerResponse>();
                    default:
                        return (object)sr;
                }
            })
                                    .ToList();
        }
    }
}

ConferencePlanner/Pages/Session.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using ConferenceDTO;
using ConferencePlanner.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ConferencePlanner.Pages
{
    public class SessionModel : PageModel
    {
        private readonly IApiClient _apiClient;

        private readonly HtmlEncoder _htmlEncoder;

        public bool IsInPersonalAgenda { get; set; }

        public SessionResponse Session { get; set; }

        public int? DayOffset { get; set; }

        public SessionModel(IApiClient apiClient, HtmlEncoder htmlEncoder)
        {
            _apiClient = apiClient;
            _htmlEncoder = htmlEncoder;
        }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Session = await _apiClient.GetSessionAsync(id);

            if (Session == null)
            {
                return RedirectToPage("/Index");
            }

            var sessions = await _apiClient.GetSessionsByAttendeeAsync(User.Identity.Name);

            var allSessions = await _apiClient.GetSessionsAsync();

            var startDate = allSessions.Min(s => s.StartTime?.Date);

            IsInPersonalAgenda = sessions.Any(s => s.ID == id);
            DayOffset = Session.StartTime?.DateTime.Subtract(startDate ?? DateTime.MinValue).Days;

            if (!string.IsNullOrEmpty(Session.Abstract))
            {
                var encodedCrLf = _htmlEncoder.Encode("\r\n");
                var encodedAbstract = _htmlEncoder.Encode(Session.Abstract);
                Session.Abstract = "<p>" + String.Join("</p><p>", encodedAbstract.Split(encodedCrLf, StringSplitOptions.RemoveEmptyEntries)) + "</p>";
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int sessionId)
        {
            await _apiClient.AddSessionToAttendeeAsync(User.Identity.Name, sessionId);

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRemoveAsync(int sessionId)
        {
            await _apiClient.RemoveSessionFromAttendeeAsync(User.Identity.Name, sessionId);

            return RedirectToPage();
        }
    }
}

ConferencePlanner/Pages/Speaker.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ConferenceDTO;
using ConferencePlanner.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ConferencePlanner.Pages
{
    public class SpeakerModel : PageModel
    {
        private readonly IApiClient _apiClient;

        public SpeakerModel(IApiClient apiClient)
        {
            _apiClient = apiClient;
        }

        public SpeakerResponse Speaker { get; set; }

        public async Task<IActionResult> OnGet(int id)
        {
            Speaker = await _apiClient.GetSpeakerAsync(id);

            if (Speaker == null)
            {
                return NotFound();
            }

            return Page();
        }
    }
}

ConferencePlanner/Pages/Speakers.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ConferenceDTO;
using ConferencePlanner.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ConferencePlanner.Pages
{
    public class SpeakersModel : PageModel
    {
        private readonly IApiClient _apiClient;

        public SpeakersModel(IApiClient apiClient)
        {
            _apiClient = apiClient;
        }

        public IEnumerable<SpeakerResponse> Speakers { get; set; }

        public async Task OnGet()
        {
            var speakers = await _apiClient.GetSpeakersAsync();

            Speakers = speakers.OrderBy(s => s.Name);
        }
    }
}

ConferencePlanner/Pages/Welcome.cshtml.cs
using System.Threading.Tasks;
using ConferenceDTO;
using ConferencePlanner.Filters;
using ConferencePlanner.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ConferencePlanner.Pages
{
    [SkipWelcome]
    public class WelcomeModel : PageModel
    {
        private readonly IApiClient _apiClient;

        public WelcomeModel(IApiClient apiClient)
        {
            _apiClient = apiClient;
        }

        [BindProperty]
        public Attendee Attendee { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            // Redirect to home page if user is anonymous or already registered as attendee
            var attendee = User.Identity.IsAuthenticated
                ? await _apiClient.GetAttendeeAsync(HttpContext.User.Identity.Name)
                : null;

            if (!User.Identity.IsAuthenticated || attendee != null)
            {
                return RedirectToPage("/Index");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await _apiClient.AddAttendeeAsync(Attendee);

            return RedirectToPage("/Index");
        }
    }
}

ConferencePlanner/Pages/Index.cshtml
@page "{day:int?}"
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="agenda">
    <h1> Conference @System.DateTime.Now.Year</h1>
    @if (Model.ShowMessage)
    {
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>   </button>
            @Model.Message
        </div>
    }

    <ul class="nav nav-pills">
        @foreach (var day in Model.DayOffsets)
        {
            <li role="presentation" class="@(Model.CurrentDayOffset == day.Offset ? "active" : null)">
                <a asp-route-day="@day.Offset">@day.DayofWeek?.ToString()</a>
            </li>
        }
    </ul>

    @await  Html.PartialAsync("_SessionList", Model)
</div>

ConferencePlanner/Pages/Login.cshtml
@page
@model LoginModel
@{
    <h1>Login</h1>

    <form method="post">
        @foreach (var scheme in Model.AuthSchemes)
        {
            <button class="btn btn-default" type="submit" name="scheme" value="@scheme.Name">@scheme.DisplayName</button>
        }
    </form>
}

ConferencePlanner/Pages/MyAgenda.cshtml
@page
@model MyAgendaModel

@{
    ViewData["Title"] = "Home Page";
}
<div class="agenda">
    <h1>My Agenda @System.DateTime.Now.Year</h1>

    @await Html.PartialAsync("_NavDayPartial", Model)

    @await Html.PartialAsync("_SessionList", Model)
</div>

ConferencePlanner/Pages/Search.cshtml
@page
@using ConferenceDTO
@model SearchModel

<div class="row">
    <h1>Search</h1>
    <form method="get">
        <div class="input-group">
            <input asp-for="Term" class="form-control" />
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Go!</button>
            </span>
        </div>
    </form>
</div>
<br />
<div class="row">
    @foreach (var result in Model.SearchResults)
    {
        <div>
            @switch (result)
            {
                case SpeakerResponse speaker:
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title text-element">Speaker: <a asp-page="Speaker" asp-route-id="@speaker.ID">@speaker.Name</a></h3>
                        </div>
                        <div class="panel-body">
                            <p class="text-element">
                                @foreach (var session in speaker.Sessions)
                                {
                                    <a asp-page="/Session" asp-route-id="@session.ID"><em>@session.Title</em></a>
                                }
                            </p>
                            <p>
                                @speaker.Bio
                            </p>
                        </div>
                    </div>
                    break;

                case SessionResponse session:
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title text-element">Session: <a asp-page="Session" asp-route-id="@session.ID">@session.Title</a></h3>
                            @foreach (var speaker in session.Speakers)
                            {
                                <a asp-page="/Speaker" asp-route-id="@speaker.ID"><em>@speaker.Name</em></a>
                            }
                        </div>
                        <div class="panel-body">
                            <p class="text-element">
                                @session.Abstract
                            </p>
                        </div>
                    </div>
                    break;
            }
        </div>
    }
</div>
@section scripts
{
<script>
    $(function () {
        var textElements = $(".text-element")
            .each(function (key, value) {
                var text = this.innerHTML;
                text = text.replace("@Model.Term", "<span class='highlighted'>@Model.Term</span>")
                this.innerHTML = text; 
        });
    });
</script>
}

ConferencePlanner/Pages/Session.cshtml
@page "{id}"
@model SessionModel

<ol class="breadcrumb">
    <li><a asp-page="/Index">Agenda</a></li>
    <li><a asp-page="/Index" asp-route-day="@Model.DayOffset">Day @(Model.DayOffset + 1)</a></li>
    <li class="active">@Model.Session.Title</li>
</ol>

<h1>@Model.Session.Title</h1>
<span class="label label-default">@Model.Session.Track?.Name</span>

@foreach (var speaker in Model.Session.Speakers)
{
    <em><a asp-page="Speaker" asp-route-id="@speaker.ID">@speaker.Name</a></em>
}

@Html.Raw(Model.Session.Abstract)

<form method="post">
    <input type="hidden" name="sessionId" value="@Model.Session.ID" />
    <p>
        <a authz-policy="Admin" asp-page="/Admin/EditSession" asp-route-id="@Model.Session.ID" class="btn btn-default btn-sm">Edit</a>
        @if (Model.IsInPersonalAgenda)
        {
            <button authz="true" type="submit" asp-page-handler="Remove" class="btn btn-default btn-sm" title="Remove from my personal agenda">
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            </button>
        }
        else
        {
            <button authz="true" type="submit" class="btn btn-default btn-sm" title="Add to my personal agenda">
                <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
            </button>
        }
    </p>
</form>    

ConferencePlanner/Pages/Speaker.cshtml
@page "{id}"
@model SpeakerModel

<ol class="breadcrumb">
    <li><a asp-page="/Speakers">Speakers</a></li>
    <li class="active">@Model.Speaker.Name</li>
</ol>

<h2>@Model.Speaker.Name</h2>

<p>@Model.Speaker.Bio</p>

<h3>Sessions</h3>
<div class="row">
    <div class="col-md-5">
        <ul class="list-group">
            @foreach (var session in Model.Speaker.Sessions)
            {
                <li class="list-group-item"><a asp-page="Session" asp-route-id="@session.ID">@session.Title</a></li>
            }
        </ul>
    </div>
</div>

ConferencePlanner/Pages/Speakers.cshtml
@page
@model SpeakersModel
@{
    ViewData["Title"] = "Speakers";
}

<div class="speaker-list">
    <h1>Speakers for Conference @System.DateTime.Now.Year</h1>

    <div class="row">
        @foreach (var speaker in Model.Speakers)
        {
            <div class="col-md-3">
                <div class="panel panel-default speaker">
                    <div class="panel-body">
                        <h3 class="panel-title"><a asp-page="Speaker" asp-route-id="@speaker.ID">@speaker.Name</a></h3>
                        <ul>
                            @foreach (var session in speaker.Sessions)
    {
                            <li><em><a asp-page="Session" asp-route-id="@session.ID">@session.Title</a></em></li>
}
                        </ul>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

ConferencePlanner/Pages/Welcome.cshtml
@page
@using ConferenceDTO
@model WelcomeModel

<h2>Welcome @User.Identity.Name</h2>
<p>
    Register as an attendee to get access to cool features.
</p>

<form method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <input asp-for="Attendee.UserName" value="@User.Identity.Name" type="hidden" />
    <div class="form-group">
        <label asp-for="Attendee.FirstName" class="control-label"></label>
        <div class="row">
            <div class="col-md-6">
                <input asp-for="Attendee.FirstName" class="form-control" />
            </div>
        </div>
        <span asp-validation-for="Attendee.FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Attendee.LastName" class="control-label"></label>
        <div class="row">
            <div class="col-md-6">
                <input asp-for="Attendee.LastName" class="form-control" />
            </div>
        </div>
        <span asp-validation-for="Attendee.LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Attendee.EmailAddress" class="control-label"></label>
        <div class="row">
            <div class="col-md-6">
                <input asp-for="Attendee.EmailAddress" class="form-control" />
            </div>
        </div>
        <span asp-validation-for="Attendee.EmailAddress" class="text-danger"></span>
    </div>
    <div class="form-group">
        <div class="">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>
</form>

@section Scripts {
    @Html.Partial("_ValidationScriptsPartial")
}

ConferencePlanner/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConferencePlanner</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">My Conference @System.DateTime.Now.Year</a>
            </div>
            
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/MyAgenda">My Agenda</a></li>
                    <li><a asp-page="/Search">Search</a></li>
                    <li><a asp-page="/Speakers">Speakers</a></li>
                </ul>
                <form asp-controller="account" asp-action="logout" method="post" id="logoutForm" class="navbar-right">
                    <ul class="nav navbar-nav navbar-right">
                        <li authz="true"><a>@Context.User.Identity.Name</a></li>
                        <li authz="true">
                            <button type="submit" class="btn btn-link navbar-btn navbar-link">Log out</button>
                        </li>
                        <li authz="false"><a asp-page="/Login">Log in</a></li>
                    </ul>
                </form>

            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - ConferencePlanner</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

ConferencePlanner/Pages/_NavDayPartial.cshtml
@model IndexModel

<ul class="nav nav-pills">
    @foreach (var day in Model.DayOffsets)
    {
        <li role="presentation" class="@(Model.CurrentDayOffset == day.Offset ? "active" : null)">
            <a asp-route-day="@day.Offset">@day.DayofWeek?.ToString()</a>
        </li>
    }
</ul>

ConferencePlanner/Pages/_SessionList.cshtml
@model IndexModel
@foreach (var timeSlot in Model.Sessions)
{
    <h4>@timeSlot.Key?.ToString("HH:mm")</h4>
    <div class="row">
        @foreach (var session in timeSlot)
        {
            <div class="col-md-3">
                <div class="panel panel-default session">
                    <div class="panel-body">
                        <p>@session.Track?.Name</p>
                        <h3 class="panel-title"><a asp-page="Session" asp-route-id="@session.ID">@session.Title</a></h3>
                        <p>

                            @foreach (var speaker in session.Speakers)
                            {
                                <em><a asp-page="Speaker" asp-route-id="@speaker.ID">@speaker.Name</a></em>
                            }
                            </p>

                        <form method="post">
                            <input type="hidden" name="sessionId" value="@session.ID" />
                            <p>
                                <a authz-policy="Admin" asp-page="/Admin/EditSession" asp-route-id="@session.ID" class="btn btn-default btn-sm">Edit</a>
                                @if (Model.UserSessions.Contains(session.ID))
                                {
                                    <button authz="true" type="submit" asp-page-handler="Remove" asp-route-day="@Model.CurrentDayOffset" class="btn btn-default btn-sm" title="Remove from my personal agenda">
                                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                                    </button>
                                }
                                else
                                {
                                    <button authz="true" type="submit" class="btn btn-default btn-sm" title="Add to my personal agenda">
                                        <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
                                    </button>
                                }
                            </p>
                        </form>
                    </div>
                </div>
            </div>
        }
    </div>
}